spring.application.name=learn-spring-boot
logging.level.org.springframework=debug
spring.profiles.active=dev

currency-service.url=https://kakelay-dev.vercel.app/
currency-service.username=default-username
currency-service.key=default-key


management.endpoints.web.exposure.include=*