
#logging.level.org.springframework=debug
#spring.profiles.active=dev

currency-service.url=https://kakelay-dev.vercel.app/
currency-service.username=default-username
currency-service.key=default-key

#management.endpoints.web.exposure.include=*
#or can use a specific path you want to use:
#management.endpoints.web.exposure.include=health,metrics

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
#use for create table as you wrote: SQL: create table course (id bigint, name varchar(255) not null, author varchar(255) not null, primary key (id) )
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

server.address=0.0.0.0
server.port=8080
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
logging.level.org.springframework=info
logging.level.com.in28minutes.springboot.myfirstwebapp=info



