logging.level.org.springframework=info

currency-service.url=https://prod.kakelay.com
currency-service.username=prod-username
currency-service.key=prod-key

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
logging.level.com.in28minutes.springboot.myfirstwebapp=info
spring.messages.encoding=UTF-8