-- 1. Subjects first
create table subjects
(
    id bigint generated by default as identity,
    name varchar(255) not null,
    author varchar(255) not null,
    primary key (id)
);

-- 2. Teachers next
create table teacher
(
    id bigint generated by default as identity,
    full_name varchar(255) not null,
    department varchar(255),
    primary key (id)
);

-- 3. Students
create table student
(
    id bigint generated by default as identity,
    full_name varchar(255) not null,
    email varchar(255) unique not null,
    enrolled_date date not null,
    primary key (id)
);

-- 4. Courses (depends on subjects + teacher)
create table course
(
    id bigint generated by default as identity,
    name varchar(255) not null,
    author varchar(255) not null,
    subject_id bigint,
    teacher_id bigint,
    primary key (id),
    foreign key (subject_id) references subjects(id),
    foreign key (teacher_id) references teacher(id)
);

-- 5. Enrollments (depends on student + course)
create table enrollment
(
    id bigint generated by default as identity,
    student_id bigint not null,
    course_id bigint not null,
    enroll_date date not null,
    primary key (id),
    foreign key (student_id) references student(id),
    foreign key (course_id) references course(id)
);
